name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install deps
      run: sudo apt-get install dos2unix

    - name: Install splat deps
      run: pip3 install -r ./splat/requirements.txt

    - name: Install dosemu
      run: |
        git clone https://github.com/sozud/dosemu-deb.git
        cd dosemu-deb
        sudo apt-get install xfonts-utils
        sudo dpkg -i fdpp_1.6-1_amd64.deb
        sudo dpkg -i fdpp-dev_1.6-1_amd64.deb
        sudo dpkg -i comcom32_0.1~alpha3-1_all.deb
        sudo dpkg -i dosemu2_2.0~pre9-1_amd64.deb

    - name: Build
      run: sh split.sh
